CREATE TABLE IF NOT EXISTS employees (
  id serial PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  title VARCHAR(40) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id serial PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  surname VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS availability (
  id serial PRIMARY KEY,
  employee_id INT NOT NULL REFERENCES employees (id) ON DELETE CASCADE,
  datetime TIMESTAMP NOT NULL,
  duration INTERVAL NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (employee_id, datetime)
);

CREATE TABLE IF NOT EXISTS booking_types (
  id serial PRIMARY KEY,
  title VARCHAR(40) NOT NULL,
  description TEXT NOT NULL,
  fixed BOOL NOT NULL,
  cost MONEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bookings (
  id serial PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  availability_slot INT NOT NULL REFERENCES availability (id) ON DELETE CASCADE,
  type_id INT NOT NULL REFERENCES booking_types (id) ON DELETE CASCADE,
  paid BOOL NOT NULL,
  cost MONEY NOT NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_edited TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

