// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID         int32            `json:"id"`
	EmployeeID int32            `json:"employee_id"`
	Datetime   pgtype.Timestamp `json:"datetime"`
	TypeID     int32            `json:"type_id"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastEdited pgtype.Timestamp `json:"last_edited"`
}

type Booking struct {
	ID         int32            `json:"id"`
	UserID     int32            `json:"user_id"`
	TypeID     int32            `json:"type_id"`
	Paid       bool             `json:"paid"`
	Cost       int32            `json:"cost"`
	Notes      pgtype.Text      `json:"notes"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastEdited pgtype.Timestamp `json:"last_edited"`
}

type BookingSlot struct {
	BookingID          int32 `json:"booking_id"`
	AvailabilitySlotID int32 `json:"availability_slot_id"`
}

type BookingType struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Fixed       bool             `json:"fixed"`
	Cost        int32            `json:"cost"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastEdited  pgtype.Timestamp `json:"last_edited"`
}

type Employee struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Surname     string           `json:"surname"`
	Email       string           `json:"email"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastLogin   pgtype.Timestamp `json:"last_login"`
}

type Role struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

type Session struct {
	ID           int32            `json:"id"`
	UserID       int32            `json:"user_id"`
	SessionToken string           `json:"session_token"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
}

type User struct {
	ID             int32            `json:"id"`
	Name           string           `json:"name"`
	Surname        string           `json:"surname"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	LastLogin      pgtype.Timestamp `json:"last_login"`
}

type UserRole struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}
