// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID         int32            `json:"id"`
	EmployeeID int32            `json:"employee_id"`
	Datetime   pgtype.Timestamp `json:"datetime"`
	Duration   pgtype.Interval  `json:"duration"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastEdited pgtype.Timestamp `json:"last_edited"`
}

type Booking struct {
	ID               int32            `json:"id"`
	UserID           int32            `json:"user_id"`
	AvailabilitySlot int32            `json:"availability_slot"`
	TypeID           int32            `json:"type_id"`
	Paid             bool             `json:"paid"`
	Cost             pgtype.Numeric   `json:"cost"`
	Notes            pgtype.Text      `json:"notes"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	LastEdited       pgtype.Timestamp `json:"last_edited"`
}

type BookingType struct {
	ID          int32            `json:"id"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	Fixed       bool             `json:"fixed"`
	Cost        pgtype.Numeric   `json:"cost"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastEdited  pgtype.Timestamp `json:"last_edited"`
}

type Employee struct {
	ID          int32            `json:"id"`
	Name        string           `json:"name"`
	Title       string           `json:"title"`
	Description string           `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastLogin   pgtype.Timestamp `json:"last_login"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Surname   string           `json:"surname"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	LastLogin pgtype.Timestamp `json:"last_login"`
}
