// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stats.sql

package db

import (
	"context"
)

const totalBookings = `-- name: TotalBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
`

type TotalBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalBookings(ctx context.Context) (TotalBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalBookings)
	var i TotalBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalCancelledBookings = `-- name: TotalCancelledBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status = 'cancelled'
`

type TotalCancelledBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalCancelledBookings(ctx context.Context) (TotalCancelledBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalCancelledBookings)
	var i TotalCancelledBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalCompletedBookings = `-- name: TotalCompletedBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status = 'completed'
`

type TotalCompletedBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalCompletedBookings(ctx context.Context) (TotalCompletedBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalCompletedBookings)
	var i TotalCompletedBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalConfirmedBookings = `-- name: TotalConfirmedBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status = 'confirmed'
`

type TotalConfirmedBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalConfirmedBookings(ctx context.Context) (TotalConfirmedBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalConfirmedBookings)
	var i TotalConfirmedBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalCreatedBookings = `-- name: TotalCreatedBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status = 'created'
`

type TotalCreatedBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalCreatedBookings(ctx context.Context) (TotalCreatedBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalCreatedBookings)
	var i TotalCreatedBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalOpenBookings = `-- name: TotalOpenBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status != 'cancelled'
`

type TotalOpenBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalOpenBookings(ctx context.Context) (TotalOpenBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalOpenBookings)
	var i TotalOpenBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalOpenNotPaidBookings = `-- name: TotalOpenNotPaidBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status != 'cancelled' and paid=false
`

type TotalOpenNotPaidBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalOpenNotPaidBookings(ctx context.Context) (TotalOpenNotPaidBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalOpenNotPaidBookings)
	var i TotalOpenNotPaidBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalOpenPaidBookings = `-- name: TotalOpenPaidBookings :one
SELECT 
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE status != 'cancelled' and paid=true
`

type TotalOpenPaidBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalOpenPaidBookings(ctx context.Context) (TotalOpenPaidBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalOpenPaidBookings)
	var i TotalOpenPaidBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}
