// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const totalBookings = `-- name: TotalBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
`

type TotalBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalBookings(ctx context.Context) (TotalBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalBookings)
	var i TotalBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalBookingsBy = `-- name: TotalBookingsBy :many
SELECT
  COALESCE(o.date, c.date)::timestamp as date,
  COALESCE(c.count, 0) + COALESCE(o.count, 0) as count,
  COALESCE(c.sum, 0) + COALESCE(o.sum, 0) as sum
FROM
  (
    SELECT
      date_trunc($1::text, a.datetime)::timestamp as date,
      COUNT(*) as count,
      sum(b.cost) as sum
    FROM
      bookings as b
      RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
      LEFT JOIN availability as a on bs.availability_slot_id = a.id
    GROUP BY
      date_trunc($1::text, a.datetime)::timestamp
  ) as o
  FULL OUTER JOIN (
    SELECT
      date_trunc($1::text, bh.start_time)::timestamp as date,
      COUNT(*) as count,
      sum(b.cost) as sum
    FROM
      bookings as b
      LEFT JOIN booking_history as bh on b.id = bh.booking_id
    WHERE
      b.status = 'cancelled'
      and bh.status = 'cancelled'
    GROUP BY
      date_trunc($1::text, bh.start_time)::timestamp
  ) as c on o.date = c.date
`

type TotalBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int32            `json:"count"`
	Sum   int32            `json:"sum"`
}

func (q *Queries) TotalBookingsBy(ctx context.Context, dollar_1 string) ([]TotalBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalBookingsByRow
	for rows.Next() {
		var i TotalBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalCancelledBookings = `-- name: TotalCancelledBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status = 'cancelled'
`

type TotalCancelledBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalCancelledBookings(ctx context.Context) (TotalCancelledBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalCancelledBookings)
	var i TotalCancelledBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalCancelledBookingsBy = `-- name: TotalCancelledBookingsBy :many
SELECT
  date_trunc($1::text, bh.start_time)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  LEFT JOIN booking_history as bh on b.id = bh.booking_id
WHERE
  b.status = 'cancelled'
  and bh.status = 'cancelled'
GROUP BY
  date_trunc($1::text, bh.start_time)::timestamp
`

type TotalCancelledBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalCancelledBookingsBy(ctx context.Context, dollar_1 string) ([]TotalCancelledBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalCancelledBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalCancelledBookingsByRow
	for rows.Next() {
		var i TotalCancelledBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalCompletedBookings = `-- name: TotalCompletedBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status = 'completed'
`

type TotalCompletedBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalCompletedBookings(ctx context.Context) (TotalCompletedBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalCompletedBookings)
	var i TotalCompletedBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalCompletedBookingsBy = `-- name: TotalCompletedBookingsBy :many
SELECT
  date_trunc($1::text, a.datetime)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
  LEFT JOIN availability as a on bs.availability_slot_id = a.id
WHERE
  b.status = 'completed'
GROUP BY
  date_trunc($1::text, a.datetime)::timestamp
`

type TotalCompletedBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalCompletedBookingsBy(ctx context.Context, dollar_1 string) ([]TotalCompletedBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalCompletedBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalCompletedBookingsByRow
	for rows.Next() {
		var i TotalCompletedBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalConfirmedBookings = `-- name: TotalConfirmedBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status = 'confirmed'
`

type TotalConfirmedBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalConfirmedBookings(ctx context.Context) (TotalConfirmedBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalConfirmedBookings)
	var i TotalConfirmedBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalConfirmedBookingsBy = `-- name: TotalConfirmedBookingsBy :many
SELECT
  date_trunc($1::text, a.datetime)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
  LEFT JOIN availability as a on bs.availability_slot_id = a.id
WHERE
  b.status = 'comfirmed'
GROUP BY
  date_trunc($1::text, a.datetime)::timestamp
`

type TotalConfirmedBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalConfirmedBookingsBy(ctx context.Context, dollar_1 string) ([]TotalConfirmedBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalConfirmedBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalConfirmedBookingsByRow
	for rows.Next() {
		var i TotalConfirmedBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalCreatedBookings = `-- name: TotalCreatedBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status = 'created'
`

type TotalCreatedBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalCreatedBookings(ctx context.Context) (TotalCreatedBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalCreatedBookings)
	var i TotalCreatedBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalCreatedBookingsBy = `-- name: TotalCreatedBookingsBy :many
SELECT
  date_trunc($1::text, a.datetime)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
  LEFT JOIN availability as a on bs.availability_slot_id = a.id
WHERE
  b.status = 'created'
GROUP BY
  date_trunc($1::text, a.datetime)::timestamp
`

type TotalCreatedBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalCreatedBookingsBy(ctx context.Context, dollar_1 string) ([]TotalCreatedBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalCreatedBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalCreatedBookingsByRow
	for rows.Next() {
		var i TotalCreatedBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalOpenBookings = `-- name: TotalOpenBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status != 'cancelled'
`

type TotalOpenBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalOpenBookings(ctx context.Context) (TotalOpenBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalOpenBookings)
	var i TotalOpenBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalOpenBookingsBy = `-- name: TotalOpenBookingsBy :many
SELECT
  date_trunc($1::text, a.datetime)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
  LEFT JOIN availability as a on bs.availability_slot_id = a.id
GROUP BY
  date_trunc($1::text, a.datetime)::timestamp
`

type TotalOpenBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalOpenBookingsBy(ctx context.Context, dollar_1 string) ([]TotalOpenBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalOpenBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalOpenBookingsByRow
	for rows.Next() {
		var i TotalOpenBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalOpenNotPaidBookings = `-- name: TotalOpenNotPaidBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status != 'cancelled'
  and paid = false
`

type TotalOpenNotPaidBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalOpenNotPaidBookings(ctx context.Context) (TotalOpenNotPaidBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalOpenNotPaidBookings)
	var i TotalOpenNotPaidBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalOpenNotPaidBookingsBy = `-- name: TotalOpenNotPaidBookingsBy :many
SELECT
  date_trunc($1::text, a.datetime)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
  LEFT JOIN availability as a on bs.availability_slot_id = a.id
WHERE
  b.paid = false
GROUP BY
  date_trunc($1::text, a.datetime)::timestamp
`

type TotalOpenNotPaidBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalOpenNotPaidBookingsBy(ctx context.Context, dollar_1 string) ([]TotalOpenNotPaidBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalOpenNotPaidBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalOpenNotPaidBookingsByRow
	for rows.Next() {
		var i TotalOpenNotPaidBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalOpenPaidBookings = `-- name: TotalOpenPaidBookings :one
SELECT
  COUNT(*) as total_count,
  SUM(cost) as total_cost
FROM
  bookings
WHERE
  status != 'cancelled'
  and paid = true
`

type TotalOpenPaidBookingsRow struct {
	TotalCount int64 `json:"total_count"`
	TotalCost  int64 `json:"total_cost"`
}

func (q *Queries) TotalOpenPaidBookings(ctx context.Context) (TotalOpenPaidBookingsRow, error) {
	row := q.db.QueryRow(ctx, totalOpenPaidBookings)
	var i TotalOpenPaidBookingsRow
	err := row.Scan(&i.TotalCount, &i.TotalCost)
	return i, err
}

const totalOpenPaidBookingsBy = `-- name: TotalOpenPaidBookingsBy :many
SELECT
  date_trunc($1::text, a.datetime)::timestamp as date,
  COUNT(*) as count,
  sum(b.cost) as sum
FROM
  bookings as b
  RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
  LEFT JOIN availability as a on bs.availability_slot_id = a.id
WHERE
  b.paid = true
GROUP BY
  date_trunc($1::text, a.datetime)::timestamp
`

type TotalOpenPaidBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int64            `json:"count"`
	Sum   int64            `json:"sum"`
}

func (q *Queries) TotalOpenPaidBookingsBy(ctx context.Context, dollar_1 string) ([]TotalOpenPaidBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalOpenPaidBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalOpenPaidBookingsByRow
	for rows.Next() {
		var i TotalOpenPaidBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalPaidBookingsBy = `-- name: TotalPaidBookingsBy :many
SELECT
  COALESCE(o.date, c.date)::timestamp as date,
  COALESCE(c.count, 0) + COALESCE(o.count, 0) as count,
  COALESCE(c.sum, 0) + COALESCE(o.sum, 0) as sum
FROM
  (
    SELECT
      date_trunc($1::text, a.datetime)::timestamp as date,
      COUNT(*) as count,
      sum(b.cost) as sum
    FROM
      bookings as b
      RIGHT JOIN booking_slots as bs on bs.booking_id = b.id
      LEFT JOIN availability as a on bs.availability_slot_id = a.id
    WHERE
      b.paid = true
    GROUP BY
      date_trunc($1::text, a.datetime)::timestamp
  ) as o
  FULL OUTER JOIN (
    SELECT
      date_trunc($1::text, bh.start_time)::timestamp as date,
      COUNT(*) as count,
      sum(b.cost) as sum
    FROM
      bookings as b
      LEFT JOIN booking_history as bh on b.id = bh.booking_id
    WHERE
      b.status = 'cancelled'
      and bh.status = 'cancelled'
      and bh.paid = true
    GROUP BY
      date_trunc($1::text, bh.start_time)::timestamp
  ) as c on o.date = c.date
`

type TotalPaidBookingsByRow struct {
	Date  pgtype.Timestamp `json:"date"`
	Count int32            `json:"count"`
	Sum   int32            `json:"sum"`
}

func (q *Queries) TotalPaidBookingsBy(ctx context.Context, dollar_1 string) ([]TotalPaidBookingsByRow, error) {
	rows, err := q.db.Query(ctx, totalPaidBookingsBy, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalPaidBookingsByRow
	for rows.Next() {
		var i TotalPaidBookingsByRow
		if err := rows.Scan(&i.Date, &i.Count, &i.Sum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
