// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO
  user_roles (user_id, role_id)
VALUES
  ($1, $2)
`

type AssignRoleToUserParams struct {
	UserID int32 `json:"user_id"`
	RoleID int32 `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const createNewRoleRequest = `-- name: CreateNewRoleRequest :one
INSERT INTO
  role_requests (user_id, requested_role_id, comment)
VALUES
  ($1, $2, $3)
RETURNING
  id
`

type CreateNewRoleRequestParams struct {
	UserID          int32       `json:"user_id"`
	RequestedRoleID int32       `json:"requested_role_id"`
	Comment         pgtype.Text `json:"comment"`
}

func (q *Queries) CreateNewRoleRequest(ctx context.Context, arg CreateNewRoleRequestParams) (int32, error) {
	row := q.db.QueryRow(ctx, createNewRoleRequest, arg.UserID, arg.RequestedRoleID, arg.Comment)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO
  sessions (user_id, session_token, expires_at)
VALUES
  ($1, $2, $3)
RETURNING
  id
`

type CreateSessionParams struct {
	UserID       int32            `json:"user_id"`
	SessionToken string           `json:"session_token"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.SessionToken, arg.ExpiresAt)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (name, surname, email, hashed_password)
VALUES
  ($1, $2, $3, $4)
RETURNING
  id
`

type CreateUserParams struct {
	Name           string `json:"name"`
	Surname        string `json:"surname"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.HashedPassword,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE
  expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM sessions
WHERE
  session_token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, sessionToken string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, sessionToken)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions
WHERE
  user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE
  id = $1
RETURNING
  id
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const getAllEmployees = `-- name: GetAllEmployees :many
SELECT
  id, name, surname, email, title, description, created_at, last_login
FROM
  employees
`

func (q *Queries) GetAllEmployees(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.Query(ctx, getAllEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Surname,
			&i.Email,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.LastLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRoleRequests = `-- name: GetAllRoleRequests :one
SELECT
  id, user_id, requested_role_id, status, comment, approved_by, created_at, approved_at
FROM
  role_requests
`

func (q *Queries) GetAllRoleRequests(ctx context.Context) (RoleRequest, error) {
	row := q.db.QueryRow(ctx, getAllRoleRequests)
	var i RoleRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedRoleID,
		&i.Status,
		&i.Comment,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT
  id, name, surname, email, title, description, created_at, last_login
FROM
  employees
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetEmployeeById(ctx context.Context, id int32) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, id)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getLatestSession = `-- name: GetLatestSession :one
SELECT
  id, user_id, session_token, created_at, expires_at
FROM
  sessions
WHERE
  user_id = $1 -- Replace 123 with the specific user ID
ORDER BY
  created_at DESC
LIMIT
  1
`

func (q *Queries) GetLatestSession(ctx context.Context, userID int32) (Session, error) {
	row := q.db.QueryRow(ctx, getLatestSession, userID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT
  id
FROM
  roles
WHERE
  name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (int32, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getRoleRequestByID = `-- name: GetRoleRequestByID :one
SELECT
  id, user_id, requested_role_id, status, comment, approved_by, created_at, approved_at
FROM
  role_requests
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetRoleRequestByID(ctx context.Context, id int32) (RoleRequest, error) {
	row := q.db.QueryRow(ctx, getRoleRequestByID, id)
	var i RoleRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedRoleID,
		&i.Status,
		&i.Comment,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getRoleRequestByUser = `-- name: GetRoleRequestByUser :one
SELECT
  id, user_id, requested_role_id, status, comment, approved_by, created_at, approved_at
FROM
  role_requests
WHERE
  user_id = $1
  AND requested_role_id = $2
LIMIT
  1
`

type GetRoleRequestByUserParams struct {
	UserID          int32 `json:"user_id"`
	RequestedRoleID int32 `json:"requested_role_id"`
}

func (q *Queries) GetRoleRequestByUser(ctx context.Context, arg GetRoleRequestByUserParams) (RoleRequest, error) {
	row := q.db.QueryRow(ctx, getRoleRequestByUser, arg.UserID, arg.RequestedRoleID)
	var i RoleRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RequestedRoleID,
		&i.Status,
		&i.Comment,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const getRolesForUser = `-- name: GetRolesForUser :many
SELECT
  r.name
FROM
  roles r
  JOIN user_roles ur ON ur.role_id = r.id
WHERE
  ur.user_id = $1
`

func (q *Queries) GetRolesForUser(ctx context.Context, userID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT
  id, user_id, session_token, created_at, expires_at
FROM
  sessions
WHERE
  session_token = $1
`

func (q *Queries) GetSessionByToken(ctx context.Context, sessionToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, sessionToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id, name, surname, email, hashed_password, created_at, last_login
FROM
  users
WHERE
  email = $1
LIMIT
  1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT
  id, name, surname, email, hashed_password, created_at, last_login
FROM
  users
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetUserById(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Surname,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const updateRoleRequest = `-- name: UpdateRoleRequest :one
UPDATE role_requests
SET
  status = $2,
  approved_at = $3,
  comment = $4
WHERE
  id = $1
RETURNING
  id
`

type UpdateRoleRequestParams struct {
	ID         int32             `json:"id"`
	Status     RoleRequestStatus `json:"status"`
	ApprovedAt pgtype.Timestamp  `json:"approved_at"`
	Comment    pgtype.Text       `json:"comment"`
}

func (q *Queries) UpdateRoleRequest(ctx context.Context, arg UpdateRoleRequestParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateRoleRequest,
		arg.ID,
		arg.Status,
		arg.ApprovedAt,
		arg.Comment,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  id = $1,
  name = $2,
  surname = $3,
  email = $4,
  hashed_password = $5,
  created_at = DEFAULT,
  last_login = DEFAULT
WHERE
  id = $1
RETURNING
  id
`

type UpdateUserParams struct {
	ID             int32  `json:"id"`
	Name           string `json:"name"`
	Surname        string `json:"surname"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Surname,
		arg.Email,
		arg.HashedPassword,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
